query global {
	globalCollection(limit: 1) {
		items {
			seoDescription
			seoImage {
				...contentfullImage
			}
			seoTitle
			seoTitleTemplate
		}
	}
}

query pageHome {
	pageHomeCollection(limit: 1) {
		items {
			contentAreaCollection {
				items {
					...blockAbout
					...blockImage
					...blockProjectsSection
					...blockServices
					...blockTimeline
				}
			}
		}
	}
}

query pageProject($slug: String!) {
	projectCollection(where: { seo: { slug: $slug } }, limit: 1) {
		items {
			title
			solutions
			headerImage {
				...contentfullImage
			}
			seo {
				slug
				description
				image {
					...contentfullImage
				}
			}
			headerImage {
				...contentfullImage
			}
			contentAreaCollection(limit: 40) {
				items {
					...blockAbout
					...blockImage
					...blockProjectsSection
					...blockServices
				}
			}
		}
	}
}

fragment blockAbout on BlockAbout {
	about
	name
	subheading
	title
	image {
		...contentfullImage
	}
	__typename
}
fragment blockImage on BlockImage {
	__typename

	image {
		...contentfullImage
	}
}

fragment blockProjectsSection on BlockProjectsSection {
	projectsCollection(limit: 3) {
		items {
			title
			teaserImage {
				...contentfullImage
			}
			solutions
			seo {
				slug
			}
			sys {
				id
			}
		}
	}
	title
	__typename
}
fragment blockServices on BlockServices {
	title
	imageCollection(limit: 40) {
		items {
			...contentfullImage
		}
	}
	__typename
}
fragment blockTimeline on BlockTimeline {
	title
	enitriesCollection(limit: 40) {
		items {
			description
			fromDate
			toDate
			title
			image {
				...contentfullImage
			}
			overwriteToDateWithNow
			subHeading
		}
	}
	__typename
}
fragment contentfullImage on Asset {
	contentType
	width
	description
	url
	title
	size
	height
}
